language: node_js
node_js:
- '0.11'
before_install: 
- npm install nodeunit istanbul bower mocha -g 
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
