language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: bSrXB4FH3dmy/0VAUQpyjFHFUJ+MD624icg7L/oucC6n3qi6HDedEoYYzW2blq0euF6CU991rW6aHfif4mBo+Fnj+oIWXBK6D+60vE4rn6C+HIlaL2Q6a/UdBaE79Vno5cM4FIYTf3fU94gOYuYPDeE5+TXNsKGS1zt6WlIA1dk3roAGvgtgMEbXYVRkIPexbZ0AHYa9+U+zjvpgUZbG7ZPDGNgob8wY+l/SNr5W5rnfWBWgPKpP3+CEPMJdHluW5EPkn8wO9JCWM/ZpIWKY6L5oIM8m9e9cUhQdgjxbFBcwbzj4IRj/XE8nB3607UplFmwWNfecBnWTNlivXmK76rSzALkOYuVxao55CjX7y3ldvml6K91qhOctwHntj5bZFjPX6Nc+WDqd2ShYpQRiYbzB/Y1cjU7JiNU+vkO4IZTkJbCrweLF7asACO2Zjo7uIFuKUCgbq7gtOwasfUknAMEmXgxytZv5r+8qOcbZYy5TGax6xCp8xAVWIWeZc2Ttio9MdxQt+Vkw26sL9AziR1vKVtbxo/hl0muKw8VDm4YhDyo3pi2yVB1Cwx7lvIywroB6g6rQCUUiaekcsj3MX2xxCAO0NVnPaPmVc4/QUCv3wdsTDQaKZqmbsh2iKZSAu2saOfTnLfw+uyTAbT0uiKOOE0btY6nH8TccOkqu9KM=
